!SESSION 2018-05-16 05:02:22.470 -----------------------------------------------
eclipse.buildId=4.7.1.M20171009-0410
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_US
Framework arguments:  -product com.ti.ccstudio.branding.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product com.ti.ccstudio.branding.product

This is a continuation of log file C:\Users\sirmo\OneDrive\Cal Poly Files\9. Spring 2018\CPE 329\ZB-GM-CPE-329\Assignments\.metadata\.bak_0.log
Created Time: 2018-05-16 05:03:29.186

!ENTRY com.ti.common.core 4 0 2018-05-16 05:03:29.186
!MESSAGE debugServerDir=C:/ti/ccsv8/ccs_base/DebugServer

!ENTRY org.eclipse.launchbar.core 2 0 2018-05-16 06:10:19.192
!MESSAGE Enablement expression is missing for descriptor type org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY org.eclipse.launchbar.core 2 0 2018-05-16 06:10:19.211
!MESSAGE Enablement expression is missing for config provider for org.eclipse.cdt.debug.core.coreBuildDescriptorType

!ENTRY com.ti.ccstudio.debug 4 0 2018-05-17 01:47:14.104
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:292)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:347)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:409)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:399)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1040)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:131)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2018-05-17 01:47:14.883
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -260 @ 0x0) An attempt to connect to the XDS110 failed. The cause may be one or more of: no XDS110 is connected, invalid firmware update, invalid XDS110 serial number, or faulty USB cable. The firmware and serial number may be updated using the xdsdfu utility found in the .../ccs_base/common/uscif/xds110 directory of your installation. View the ReadMe.txt file there for instructions. (Emulation package 7.0.188.0) 


!ENTRY com.ti.ccstudio.debug 1 0 2018-05-17 01:47:15.063
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -260 @ 0x0)
An attempt to connect to the XDS110 failed.
The cause may be one or more of: no XDS110 is connected, invalid
firmware update, invalid XDS110 serial number, or faulty USB
cable. The firmware and serial number may be updated using the
xdsdfu utility found in the .../ccs_base/common/uscif/xds110
directory of your installation. View the ReadMe.txt file there
for instructions.
(Emulation package 7.0.188.0)


!ENTRY com.ti.ccstudio.debug 4 0 2018-05-17 01:49:16.936
!MESSAGE An internal error was logged by 'com.ti.ccstudio.debug'.
!STACK 0
java.util.concurrent.ExecutionException: org.json.JSONException: Module Closed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.ti.ccstudio.debug.service.ApplicationService.getConnectedDebugProbes(ApplicationService.java:292)
	at com.ti.ccstudio.debug.service.ApplicationService.detectXDS110ConnectedProbes(ApplicationService.java:347)
	at com.ti.ccstudio.debug.service.ApplicationService.initDebugger(ApplicationService.java:409)
	at com.ti.ccstudio.debug.service.ApplicationService.access$0(ApplicationService.java:399)
	at com.ti.ccstudio.debug.service.ApplicationService$ThreadContextCache.retrieve(ApplicationService.java:136)
	at com.ti.ccstudio.debug.dsf.extensions.concurrent.DataCache.wait(DataCache.java:59)
	at com.ti.ccstudio.debug.service.ApplicationService.getCpuBeingDebugged(ApplicationService.java:1040)
	at com.ti.ccstudio.debug.launch.CCSLaunchDelegate$2.execute(CCSLaunchDelegate.java:131)
	at org.eclipse.cdt.dsf.concurrent.Query.run(Query.java:177)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: Module Closed
	at com.ti.cloudagent.communication.JSONInterface.call(JSONInterface.java:54)
	at com.ti.cloudagent.Agent.createModule(Agent.java:171)
	at com.ti.cloudagent.Agent.lambda$createSpecificModule$4(Agent.java:96)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
	at com.ti.cloudagent.Agent.createSpecificModule(Agent.java:87)
	at com.ti.cloudagent.Agent.createDeviceDetector(Agent.java:76)
	... 16 more

!ENTRY com.ti.ccstudio.debug 1 0 2018-05-17 01:49:17.169
!MESSAGE DS_ERROR: CS_DAP_0: Error connecting to the target: (Error -260 @ 0x0) An attempt to connect to the XDS110 failed. The cause may be one or more of: no XDS110 is connected, invalid firmware update, invalid XDS110 serial number, or faulty USB cable. The firmware and serial number may be updated using the xdsdfu utility found in the .../ccs_base/common/uscif/xds110 directory of your installation. View the ReadMe.txt file there for instructions. (Emulation package 7.0.188.0) 


!ENTRY com.ti.ccstudio.debug 1 0 2018-05-17 01:49:17.325
!MESSAGE DS_ERROR: Error connecting to the target:
(Error -260 @ 0x0)
An attempt to connect to the XDS110 failed.
The cause may be one or more of: no XDS110 is connected, invalid
firmware update, invalid XDS110 serial number, or faulty USB
cable. The firmware and serial number may be updated using the
xdsdfu utility found in the .../ccs_base/common/uscif/xds110
directory of your installation. View the ReadMe.txt file there
for instructions.
(Emulation package 7.0.188.0)

